name: Publish Extension

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci

      - name: Package Extension
        shell: powershell
        run: |
          npx @vscode/vsce package `
            --target win32-x64 `
            --allow-package-all-secrets `
            --out extension-win32-x64.vsix `
            --verbose

      - name: Inspect VSCE
        shell: powershell
        run: |
          npx @vscode/vsce --version
          npx @vscode/vsce ls --target win32-x64

      - name: Publish Extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        shell: powershell
        run: |
          npx @vscode/vsce publish `
            --packagePath extension-win32-x64.vsix
