name: Publish Extension

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Package & Publish for Windows x64
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        shell: powershell
        run: npx @vscode/vsce publish --target win32-x64 --pat $env:VSCE_PAT